import json
import os
from typing import Any, Dict, List
from dotenv import load_dotenv
import litellm
from pgvector.psycopg import register_vector
import psycopg

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/vectordb")
# Active Gemini embedding model:
EMBEDDING_MODEL = "gemini/gemini-embedding-001"


def get_embedding(text: str) -> List[float]:
    """
    Generates a 768-dimensional dense vector embedding using Gemini via LiteLLM.
    """
    response = litellm.embedding(
        model=EMBEDDING_MODEL,
        input=[text],
        dimensions=768,  # Request 768 dimensions to match our Postgres schema
    )
    return response.data[0]["embedding"]


def ingest_documents(documents: List[Dict[str, Any]]):
    """
    Embeds documents and inserts them into PostgreSQL in a single transactional session.
    """
    print(f"Connecting to database to ingest {len(documents)} documents...")

    with psycopg.connect(DATABASE_URL) as conn:
        # Register pgvector type handler for this connection
        register_vector(conn)

        with conn.cursor() as cur:
            for idx, doc in enumerate(documents, start=1):
                content = doc["content"]
                metadata = doc.get("metadata", {})

                print(f"[{idx}/{len(documents)}] Embedding: '{content[:50]}...'")
                embedding_vector = get_embedding(content)

                if len(embedding_vector) != 768:
                    raise ValueError(
                        f"Expected 768 dimensions, got {len(embedding_vector)}"
                    )

                # Insert content, metadata (as JSON), and embedding.
                # The 'tsv' column is auto-generated by Postgres.
                cur.execute(
                    """
                    INSERT INTO documents (content, metadata, embedding)
                    VALUES (%s, %s, %s);
                    """,
                    (content, json.dumps(metadata), embedding_vector),
                )

            conn.commit()
    print("\nIngestion complete. All documents, vectors, and GIN tokens indexed.")


if __name__ == "__main__":
    sample_corpus = [
        {
            "content": "SOP-BIO-004: All staff entering the commercial rabbit breeding facility must step into the Virkon footbath. Quarantine protocol lasts 14 days for any newly arrived stock.",
            "metadata": {"doc_id": "SOP-BIO-004", "department": "Biosecurity", "type": "Policy"}
        },
        {
            "content": "Invoice INV-2026-904 from Agrico Supplies: 120 bags of grower pellets delivered to Central Depot on September 15. Total cost: 14,400 GHS. Payment status: Net 30.",
            "metadata": {"doc_id": "INV-2026-904", "department": "Finance", "type": "Invoice"}
        },
        {
            "content": "Broiler thermal management: When ambient temperatures exceed 32°C, increase ventilation fan speed and add electrolytes to the automated drinking line to reduce mortality from heat exhaustion.",
            "metadata": {"doc_id": "SOP-ENV-012", "department": "Livestock", "type": "Instruction"}
        },
        {
            "content": "Equipment Manual PUMP-TX8: The automated irrigation pump requires oil change every 250 operating hours. Use 15W-40 industrial lubricant only. Part serial: PUMP-TX8-LUB.",
            "metadata": {"doc_id": "MAN-PUMP-TX8", "department": "Maintenance", "type": "Manual"}
        },
        {
            "content": "Emergency protocol for sudden power outages: Activate the 45kVA backup generator within 8 minutes. Verify transfer switch engagement and ensure the nursery brooder lamps have continuous supply.",
            "metadata": {"doc_id": "SOP-EMG-001", "department": "Operations", "type": "Emergency"}
        }
    ]

    ingest_documents(sample_corpus)
